import 'package:flutter/material.dart';

const desc =
    'The Role  Play a central role in designing and developing major components of the next generation stream and batch processing system for Tesla.  Build and configure solutions that use Apache Kafka alongside Hadoop, Stream Processing, relational and NoSQL databases and tune them for performances at scale.  Implement data pipelines to automate the ingestion, transformation, and augmentation of both structured and unstructured data sources, and provide best practices for pipeline operations.  Work with Business Analysts, Application Developers and Data Scientists to implement solutions using agile methodologies.';
const qualification =
    '4+ years designing, building, and operating in-production Big Data, stream processing, and/or enterprise data integration solutions using Apache Kafka.';
const requirement =
    'Solid experience of building complex data pipelines.Extremely proficient in Java/Scala programming. Knowledge of Go a plus.  1+ years of hands on managing and administering Storm/Spark or Samza, Zookeeper and NoSQL storage. Proficiency with HDFS and MapReduce. Knowledge of rules based decision making, information parsing and complex data mining.  Experience engineering large scale data infrastructures. Experience contributing to open source projects and working with open source community.  Strong desire to tackle hard technical challenges and ability to work with minimum daily supervision. Strong desire to learn and implement cutting edge technology.';
const tags = [
  "sources",
  "databases",
  "data scientists",
  "augmentation",
  "batch processing system",
  "pipeline",
  "processing",
  "developers",
  "stream processing",
  "work",
  "pipeline operations",
  "solutions",
  "nosql",
  "stream",
  "hadoop",
  "generation stream",
  "application developers",
  "role",
  "components",
  "operations",
  "agile",
  "batch",
  "transformation",
  "analysts",
  "system",
  "generation",
  "pipelines",
  "application",
  "business analysts",
  "methodologies",
  "build",
  "scale",
  "data",
  "data sources",
  "ingestion",
  "practices",
  "data pipelines",
  "business",
  "scientists",
  "performances"
];
const DEFAULT_COLOR = Color(0xFF0039A5);
const DEFAULT_COLOR_1 = Color(0xFFFF6B01);
const SUB_HEAD = Color(0xFF8E8E8E);
const SUB_HEAD_1 = Colors.black87;
const ROOT = 'https://api.workanetworks.com/';
const TYPE = 'A_TYPE';
const FIRSTNAME = 'firstname';
const LASTNAME = 'lastname';
const EMAIL = 'email';
const AVATAR = 'avatar';
const CV_LINK = 'cv_link';
const PLAN = 'plan';
const JOB_DESC =
    'An expert who can design a functional and appealing user experience and interface design is urgently needed. We are looking for a graphic  designer to work on ad hoc projects to support our brand marketing team.';
const List<String> POSITIONS = [
  "Customer service representative",
  "Chief Technology Officer (CTO)",
  "Project manager",
  "Accountant",
  "Chief Marketing Officer (CMO)",
  "Chief Executive Officer (CEO)",
  "Human resource personnel",
  "Manager",
  "President",
  "Business analyst",
  "Marketing manager",
  "Marketing specialist",
  "Finance manager",
  "Product manager",
  "Chief Financial Officer (CFO) or Controller",
  "Executive assistants",
  "Vice President",
  "Administrative assistant",
  "Chief Operating Officer (COO)",
  "Human resources manager",
  "Sales representative",
  "Executive",
  "Operations and production"
];
const INDUSTRIES = [
  "Retail",
  "Sales",
  "Healthcare",
  "Public services",
  "administration",
  "Leisure, sport and tourism",
  "Transport and logistics",
  "Media, News and internet",
  "Marketing",
  "advertising",
  "public relation",
  "Information technology",
  "Charity and voluntary work",
  "education",
  "Energy and utilities",
  "Law",
  "Business, consulting and management",
  "Hospitality and events management",
  "Law enforcement and security",
  "Social care",
  "Creative arts and design",
  "Recruitment and HR",
  "Engineering",
  "manufacturing",
  "Accountancy,",
  "Banking and finance",
  "Environment",
  "Agriculture",
  "Property Management",
  "Construction",
  "Science and pharmaceuticals",
  "Advertising and marketing",
  "Aerospace",
  "Agriculture",
  "Computer and technology",
  "Entertainment",
  "Fashion",
  "Food and beverage",
  "Mining",
  "Telecommunication"
];
const ROLES = [
  'A/B Testing',
  'Accounting',
  'Accuracy',
  'Active listening',
  'Acute care',
  'Ad design',
  'Adaptability',
  'Administrative',
  'Adobe Illustrator',
  'Adobe Photoshop',
  'Advanced Cardiac Life Support (ACLS)',
  'Affiliate marketing',
  'Agile',
  'Analytical reasoning',
  'Answering Phones',
  'Anti Money Laundering',
  'Application Programming Interface (API)',
  'Art',
  'Artificial intelligence',
  'Attention to detail & aesthetics',
  'Auditing',
  'AutoCAD',
  'Automation',
  'B2B Marketing',
  'Baseball',
  'Basketball',
  'Big Data Analysis & SQL',
  'Blockchain',
  'Blood Pressure Monitoring',
  'Bookkeeping',
  'Branding',
  'Budgeting',
  'Business',
  'Business Analysis',
  'Business Development',
  'Business Intelligence',
  'Business management',
  'Business Planning',
  'Business Process',
  'Business Process Improvement',
  'Business Process Modeling',
  'Business Services',
  'Business storytelling',
  'Business Strategy',
  'Buyer engagement',
  'Buyer-Responsive selling',
  'CAD',
  'Calendar Management',
  'Cashier ',
  'Channel marketing',
  'Charisma',
  'Clear communication',
  'Closing',
  'Cloud computing',
  'Cloud Management',
  'Cloud networking and file sharing',
  'CMS Tools',
  'Coaching',
  'Cognos Analytics (IBM)',
  'Cold-calling',
  'Collaboration',
  'Color sense & theory',
  'Communication',
  'Company Research',
  'Compassion',
  'Computer ',
  'Conflict management',
  'Conflict Resolution',
  'Construction',
  'Consulting',
  'Consumer Behavior Drivers',
  'Content management',
  'Content Management Systems (CMS)',
  'Content marketing',
  'Content strategy',
  'Contract Negotiation',
  'Contractual Agreements',
  'Copywriting',
  'Creativity',
  'Critical thinking',
  'CRM Software (Salesforce, Hubspot, Zoho, Freshsales)',
  'CRO',
  'CSS preprocessors',
  'Customer Needs Analysis',
  'Customer Relationship Management',
  'Customer Service ',
  'Data Analysis',
  'Data Entry',
  'Data Mapping',
  'Data presentation',
  'Data Structures',
  'Data Visualization',
  'Databases',
  'Dealing with work-related stress',
  'Debugging',
  'Decision Making',
  'Delegating tasks',
  'Department of Defense',
  'Design',
  'Development Tools',
  'Digital Marketing',
  'Digital Media',
  'Digital printing',
  'Diving',
  'Drawing',
  'Dreamweaver',
  'Ecommerce',
  'Economics',
  'Editing',
  'Educational platforms (software like Elearn)',
  'Effective communication and sociability',
  'Electronic Heart Record (EHR)',
  'Electronic Medical Record (EMR)',
  'Electronics',
  'Email',
  'Email Automation',
  'Email marketing',
  'Emotional intelligence (EQ)',
  'Empathy',
  'Employee Benefits Design',
  'Energy',
  'Enterprise Resource Planning',
  'Enterprise Software',
  'Enthusiasm',
  'Entity Relationship Diagrams',
  'Entrepreneurship',
  'Event Planning',
  'Extroversion',
  'Facilitation',
  'Facility Management',
  'Feature Definition',
  'Filing and paper management',
  'Finance',
  'Financial Analysis',
  'Financial Modelling',
  'Financial Reporting',
  'Financial Risk',
  'Food and Beverage',
  'Football',
  'Forecasting',
  'Front-End & Back-End Development',
  'Fundraising',
  'Gas',
  'General business knowledge',
  'General Ledger',
  'General Nursing ',
  'Git/Version control (Github, gitlab)',
  'Glucose Checks',
  'Golf',
  'Good Communication ',
  'Government Agencies',
  'Grant Writing',
  'Graphic Design ',
  'Graphic User Interfaces (GUI)',
  'Grocery',
  'Gymnastics',
  'Healthcare',
  'Healthcare Management',
  'Heavy Equipment',
  'Helping Clients Succeed',
  'Higher Education',
  'History',
  'Hospitality Industry',
  'Hospitals',
  'HTML & CSS',
  'HTML5',
  'Hygiene Assistance',
  'Ideation Leadership',
  'Increasing Customer Lifetime Value (CLV)',
  'Infection control',
  'Infographics',
  'Information Systems',
  'Information Technology',
  'Innovation',
  'Insurance',
  'Integrated Marketing',
  'Integration',
  'Interactive media design',
  'Internal Audit',
  'Interpersonal ',
  'Interviewing',
  'Investments',
  'Invoicing',
  'Java',
  'Javascript',
  'Job Scanning',
  'Joint Ventures',
  'Journalism',
  'JQuery',
  'K12 Education',
  'Kanban',
  'Key Account Development',
  'Key Performance Indicators',
  'Kindergarten',
  'Know Your Customers (KYC)',
  'Knowledge Base',
  'Knowledge Management',
  'Knowledge Sharing',
  'Laboratory ',
  'Language ',
  'Lead generation',
  'Lead Prospecting',
  'Lead Qualification',
  'Leadership',
  'Lean Manufacturing',
  'Legal Writing',
  'Linux',
  'Litigation',
  'Local Marketing',
  'Logistics Management',
  'Logo creation',
  'Machine Learning',
  'Management',
  'Marine Corps',
  'Market research',
  'Mathematics',
  'Mechanical Engineering',
  'Media planning',
  'Medical Compliance',
  'Medicine Administration',
  'Meditech',
  'Meeting Facilitation',
  'Microsoft Office ',
  'Microsoft Visio',
  'Military Aviation',
  'Military Weapons',
  'Mobile development',
  'Motivation',
  'Negotiation',
  'Network Administration',
  'Network and information security',
  'Network Attached Storage',
  'Network Communications',
  'Network Systems',
  'New Business Opportunities',
  'New Hires',
  'Newsletters',
  'NIH Stroke Scale Patient Assessment',
  'Nonprofit Organizations',
  'Nonverbal communication',
  'Numerical competence',
  'Nutrition',
  'Office Administration',
  'Office Equipment',
  'Online Advertising',
  'Online marketing',
  'Open Source Experience',
  'Openness',
  'Operating Systems',
  'Operations Management',
  'Oracle Database',
  'Order Fulfillment',
  'Organizational Development',
  'Organizational Structure',
  'Organizing ',
  'Outsourcing',
  'Paid social media advertisements',
  'Paperwork/record-keeping abilities',
  'Partnerships',
  'Patience',
  'Patient Assessment',
  'Patient care and assistance',
  'Patient Education',
  'People management',
  'Performance Tracking',
  'Performance Tuning',
  'Persuasion',
  'PESTEL',
  'Phlebotomy',
  'Photo editing',
  'Photography and Branding',
  'Physical endurance',
  'Planning',
  'Porter’s Five Forces',
  'POS ',
  'PPC',
  'Presentation',
  'Pricing Strategy',
  'Print Design',
  'Problem Solving',
  'Product Knowledge',
  'Profit and Loss',
  'Program Management',
  'Programming Languages',
  'Project Launch',
  'Project Lifecycle Management',
  'Project management',
  'Project Planning',
  'Project/campaign management',
  'Proposal writing',
  'Prototyping',
  'Public Policy',
  'Public Relations',
  'Public Speaking',
  'Qualifying Prospects',
  'Qualitative Research',
  'Quality Auditing',
  'Quality Improvement',
  'Quality System',
  'Quantitative Research',
  'Query Writing',
  'Queues',
  'QuickBooks',
  'Quotations',
  'Range',
  'Real Estate',
  'Recording Patient Medical History',
  'Record-Keeping',
  'Recruiting',
  'Reducing Customer Acquisition Cost (CAC)',
  'Referral Marketing',
  'Regulations',
  'Rehabilitation Therapy',
  'Relationship management',
  'Requirements Analysis',
  'Research',
  'Research & Data analysis',
  'Residential Homes',
  'Responsibility',
  'Responsive design principles',
  'Retail',
  'Revenue recognition',
  'Reviews',
  'Sales',
  'Sales Funnel Management',
  'Sales Management',
  'Salesforce',
  'Scheduling',
  'Scientific computing',
  'Scope Management',
  'Scrum',
  'Search Engine Optimization (SEO)',
  'Security',
  'Self Motivation',
  'Shipping',
  'Six Sigma techniques',
  'Soccer',
  'Social Media Marketing  ',
  'Social Media Advertising',
  'Software',
  'Software Documentation',
  'Software engineering',
  'SolidWorks',
  'SQL',
  'Staff Development',
  'STATA, SPSS, SAS',
  'STEM ',
  'Storage systems and management',
  'Storyboarding',
  'Storytelling',
  'Strategic Management',
  'Strategic Planning',
  'Stress management',
  'Supervisory ',
  'Surgery preparation',
  'Swimming',
  'System Context Diagrams',
  'Taking Vital Signs',
  'Targeting and marketing through visual communications',
  'Task delegation',
  'Teaching',
  'Team Building',
  'Team Leadership',
  'Team Management',
  'Teamwork ',
  'Tech support',
  'Technical and non-technical communication',
  'Technical Report Writing ',
  'Technical writing',
  'Technological & digital literacy',
  'Technological savviness',
  'Telecommunications',
  'Telemetry',
  'Testing/Debugging',
  'Time Management',
  'Training',
  'Troubleshooting',
  'Typography',
  'UI/UX',
  'Underwriting',
  'Unified Modeling Language',
  'University Teaching',
  'Unix',
  'Updated curriculum knowledge',
  'Urgent and Emergency Care',
  'Use of X-Ray, MRI, CAT Scans',
  'User Acceptance Testing',
  'User Experience',
  'User Interface Design',
  'Validation',
  'Vendors',
  'Video',
  'Video Editing',
  'Video Production',
  'Visual Basic',
  'Visual Merchandising',
  'Volleyball',
  'Volunteer Management',
  'Water Resource Management',
  'Web analytics',
  'Web Applications',
  'Web Design',
  'Web Development',
  'Web scraping',
  'Welcoming Visitors',
  'Windows',
  'Windows Server',
  'Wireframes',
  'Wireless Technologies',
  'WordPress',
  'Workflow Development',
  'Workshops',
  'Wound Dressing and Care',
  'Writing'
];
