import 'package:flutter/material.dart';

class LanguageClass {
  static Iterable<String?> getLocalLanguage(search) {
    return LANGUAGES
        .where((element) =>
            element.toLowerCase().contains(search.toString().toLowerCase()))
        .toList();
  }

  static Iterable<String?> getLocalOccupation(search) {
    return OCCUPATION
        .where((element) =>
            element.toLowerCase().contains(search.toString().toLowerCase()))
        .toList();
  }
}

const PUBLIC_KEY = 'pk_live_73c691bec0868b49d857291fba4c7f33d261f5f8';
const SECRET_KEY = 'sk_live_634abcc18eb8da28c043d80b3d74c1461df4e62b';

const CONTENT =
    'You are on a  free trial, choose a plan that\'s right for you to explore all of our features';


Map<String, Map<String, dynamic>> PLAN_PRICE = {
  'Free': {
    'price': '0.00',
    'plan': '20220322',
    'color': Colors.black,
    'duration': 'Annually',
    'features': [
      'Access to five(5) shortlisted staff',
      'Access to unlimited choice of candidate',
      'Access to interview five(5) candidates',
      'Access to online test/interview',
      'Free access to candidate anywhere in the world'
    ]
  },
  'Silver Premium': {
    'price': '5000.00',
    'plan': '32282003',
    'ID': '_worka_silver_plan',
    'color': Color(0xFFC0C0C0),
    'duration': 'Annually',
    'features': [
      'Access to ten(10) shortlisted staff',
      'Access to unlimited choice of candidate',
      'Access to interview ten(10) candidates',
      'Access to online test/interview',
      'Free access to candidate anywhere in the world'
    ]
  },
  'Gold Premium': {
    'price': '10000.00',
    'plan': '12900320',
    'ID': '_worka_gold_plan',
    'color': Color(0xFFFFD700),
    'duration': 'Annually',
    'features': [
      'Access to twenty(20) shortlisted staffs',
      'Access to unlimited choice of candidate',
      'Access to interview twenty(20) candidates',
      'Access to online test/interview',
      'Free access to candidate anywhere in the world'
    ]
  },
  'Diamond': {
    'price': '20000.00',
    'plan': '40151001',
    'ID': '_worka_diamond_plan',
    'color': Color(0xFFB9F2FF),
    'duration': 'Annually',
    'features': [
      'Unlimited access to shortlisted staffs',
      'Unlimited access to choice of candidates',
      'Unlimited access to test/interview candidates',
      'Unlimited access to candidates anywhere in the world'
    ]
  }
};

const BUSINESS_SCALE_ITEM = ['small', 'medium', 'large'];

const INDUSTRY_ITEMS = [
  "Retail",
  "Sales",
  "Healthcare",
  "Public services",
  "administration",
  "Leisure, sport and tourism",
  "Transport and logistics",
  "Media, News and internet",
  "Marketing",
  "advertising",
  "public relation",
  "Information technology",
  "Charity and voluntary work",
  "education",
  "Energy and utilities",
  "Law",
  "Business, consulting and management",
  "Hospitality and events management",
  "Law enforcement and security",
  "Social care",
  "Creative arts and design",
  "Recruitment and HR",
  "Engineering",
  "manufacturing",
  "Accountancy,",
  "Banking and finance",
  "Environment",
  "Agriculture",
  "Property Management",
  "Construction",
  "Science and pharmaceuticals",
  "Advertising and marketing",
  "Aerospace",
  "Agriculture",
  "Computer and technology",
  "Entertainment",
  "Fashion",
  "Food and beverage",
  "Mining",
  "Telecommunication"
];

const BUSINESSSCALE = ['small', 'medium', 'large'];

const POSITIONITEM = [
  "Customer service representative",
  "Chief Technology Officer (CTO)",
  "Project manager",
  "Accountant",
  "Chief Marketing Officer (CMO)",
  "Chief Executive Officer (CEO)",
  "Human resource personnel",
  "Manager",
  "President",
  "Business analyst",
  "Marketing manager",
  "Marketing specialist",
  "Finance manager",
  "Product manager",
  "Chief Financial Officer (CFO) or Controller",
  "Executive assistants",
  "Vice President",
  "Administrative assistant",
  "Chief Operating Officer (COO)",
  "Human resources manager",
  "Sales representative",
  "Executive",
  "Operations and production"
];

const SILLSLEVEL = ['Novice', 'Amateur', 'Competent', 'Proficient', 'Expert'];
const COMPANY_DESC =
    'We are a global group of energy and petrochemical companies with more than 80,000 employees in more than70 countries. We use advanced technologies and take an innovative approach to help build a sustainable energy future.';
const List<String> CURRENCY = [
  "ALL",
  "AFN",
  "ARS",
  "AWG",
  "AUD",
  "AZN",
  "BSD",
  "BBD",
  "BDT",
  "BYR",
  "BZD",
  "BMD",
  "BOB",
  "BAM",
  "BWP",
  "BGN",
  "BRL",
  "BND",
  "KHR",
  "CAD",
  "KYD",
  "CLP",
  "CNY",
  "COP",
  "CRC",
  "HRK",
  "CUP",
  "CZK",
  "DKK",
  "DOP",
  "XCD",
  "EGP",
  "SVC",
  "EEK",
  "EUR",
  "FKP",
  "FJD",
  "GHC",
  "GIP",
  "GTQ",
  "GGP",
  "GYD",
  "HNL",
  "HKD",
  "HUF",
  "ISK",
  "INR",
  "IDR",
  "IRR",
  "IMP",
  "ILS",
  "JMD",
  "JPY",
  "JEP",
  "KZT",
  "KPW",
  "KRW",
  "KGS",
  "LAK",
  "LVL",
  "LBP",
  "LRD",
  "LTL",
  "MKD",
  "MYR",
  "MUR",
  "MXN",
  "MNT",
  "MZN",
  "NAD",
  "NPR",
  "ANG",
  "NZD",
  "NIO",
  "NGN",
  "NOK",
  "OMR",
  "PKR",
  "PAB",
  "PYG",
  "PEN",
  "PHP",
  "PLN",
  "QAR",
  "RON",
  "RUB",
  "SHP",
  "SAR",
  "RSD",
  "SCR",
  "SGD",
  "SBD",
  "SOS",
  "ZAR",
  "LKR",
  "SEK",
  "CHF",
  "SRD",
  "SYP",
  "TWD",
  "THB",
  "TTD",
  "TRY",
  "TRL",
  "TVD",
  "UAH",
  "GBP",
  "USD",
  "UYU",
  "UZS",
  "VEF",
  "VND",
  "YER",
  "ZWD"
];

const YEARS = [
  '1 year',
  '2 years',
  '3 years',
  '4 years',
  '5 years',
  '6 years',
  '7 years',
  '8 years',
  '9 years',
  '10 years',
  '11 years',
  '12 years',
  '13 years',
  '14 years',
  '15 years',
  '16 years',
  '17 years',
  '18 years',
  '19 years',
  '20+ years',
];
const LEVELS = [
  'Elementary',
  'High School',
  'Technician',
  'College',
  'Polytechnic',
  'University'
];

const CERTIFICATE = [
  'Leaving School',
  'O Level',
  'NCE',
  'Diploma',
  'OND',
  'Technician',
  'HND',
  'BSc',
  'BSEng',
  'BTech',
  'BEdu'
];

const LANGUAGES = [
  "Afa",
  "Abkhaz",
  "Avestan",
  "Afrikaans",
  "Akan",
  "Amharic",
  "Aragonese",
  "Arabic",
  "Assamese",
  "Avaric",
  "Aymara",
  "Azerbaijani",
  "South Azerbaijani",
  "Bashkir",
  "Belarusian",
  "Bulgarian",
  "Bihari",
  "Bislama",
  "Bambara",
  "Bengali; Bangla",
  "Tibetan Standard, Tibetan, Central",
  "Breton",
  "Bosnian",
  "Catalan; Valencian",
  "Chechen",
  "Chamorro",
  "Corsican",
  "Cree",
  "Czech",
  "Old Church Slavonic, Church Slavonic, Old Bulgarian",
  "Chuvash",
  "Welsh",
  "Danish",
  "German",
  "Divehi; Dhivehi; Maldivian;",
  "Dzongkha",
  "Ewe",
  "Greek, Modern",
  "English",
  "Esperanto",
  "Spanish; Castilian",
  "Estonian",
  "Basque",
  "Persian",
  "Fula; Fulah; Pulaar; Pular",
  "Finnish",
  "Fijian",
  "Faroese",
  "French",
  "Western Frisian",
  "Irish",
  "Scottish Gaelic; Gaelic",
  "Galician",
  "GuaranÃ­",
  "Gujarati",
  "Manx",
  "Hausa",
  "Hebrew (modern)",
  "Hindi",
  "Hiri Motu",
  "Croatian",
  "Haitian; Haitian Creole",
  "Hungarian",
  "Armenian",
  "Herero",
  "Interlingua",
  "Indonesian",
  "Interlingue",
  "Igbo",
  "Nuosu",
  "Inupiaq",
  "Ido",
  "Icelandic",
  "Italian",
  "Inuktitut",
  "Japanese",
  "Javanese",
  "Georgian",
  "Kongo",
  "Kikuyu, Gikuyu",
  "Kwanyama, Kuanyama",
  "Kazakh",
  "Kalaallisut, Greenlandic",
  "Khmer",
  "Kannada",
  "Korean",
  "Kanuri",
  "Kashmiri",
  "Kurdish",
  "Komi",
  "Cornish",
  "Kyrgyz",
  "Latin",
  "Luxembourgish, Letzeburgesch",
  "Ganda",
  "Limburgish, Limburgan, Limburger",
  "Lingala",
  "Lao",
  "Lithuanian",
  "Luba-Katanga",
  "Latvian",
  "Malagasy",
  "Marshallese",
  "MÄori",
  "Macedonian",
  "Malayalam",
  "Mongolian",
  "Marathi",
  "Malay",
  "Maltese",
  "Burmese",
  "Nauru",
  "Norwegian BokmÃ¥l",
  "North Ndebele",
  "Nepali",
  "Ndonga",
  "Dutch",
  "Norwegian Nynorsk",
  "Norwegian",
  "South Ndebele",
  "Navajo, Navaho",
  "Chichewa; Chewa; Nyanja",
  "Occitan",
  "Ojibwe, Ojibwa",
  "Oromo",
  "Oriya",
  "Ossetian, Ossetic",
  "Panjabi, Punjabi",
  "PÄli",
  "Polish",
  "Pashto, Pushto",
  "Portuguese",
  "Quechua",
  "Romansh",
  "Kirundi",
  "Romanian",
  "Russian",
  "Kinyarwanda",
  "Sanskrit",
  "Sardinian",
  "Sindhi",
  "Northern Sami",
  "Sango",
  "Sinhala, Sinhalese",
  "Slovak",
  "Slovene",
  "Samoan",
  "Shona",
  "Somali",
  "Albanian",
  "Serbian",
  "Swati",
  "Southern Sotho",
  "Sundanese",
  "Swedish",
  "Swahili",
  "Tamil",
  "Telugu",
  "Tajik",
  "Thai",
  "Tigrinya",
  "Turkmen",
  "Tagalog",
  "Tswana",
  "Tonga (Tonga Islands)",
  "Turkish",
  "Tsonga",
  "Tatar",
  "Twi",
  "Tahitian",
  "Uyghur, Uighur",
  "Ukrainian",
  "Urdu",
  "Uzbek",
  "Venda",
  "Vietnamese",
  "VolapÃ¼k",
  "Walloon",
  "Wolof",
  "Xhosa",
  "Yiddish",
  "Yoruba",
  "Zhuang, Chuang",
  "Chinese",
  "Zulu "
];

const OCCUPATION = [
  'Accountant',
  'Accounts Assistant',
  'Accounts Clerk',
  'Accounts Manager',
  'Accounts Staff',
  'Acoustic Engineer',
  'Actor',
  'Actress',
  'Actuary',
  'Acupuncturist',
  'Adjustor',
  'Administration Assistant',
  'Administration Clerk',
  'Administration Manager',
  'Administration Staff',
  'Administrator',
  'Advertising Agent',
  'Advertising Assistant',
  'Advertising Clerk',
  'Advertising Contractor',
  'Advertising Executive',
  'Advertising Manager',
  'Advertising Staff',
  'Aerial Erector',
  'Aerobic Instructor',
  'Aeronautical Engineer',
  'Agent',
  'Air Traffic Controller',
  'Aircraft Designer',
  'Aircraft Engineer',
  'Aircraft Maintenance Engineer',
  'Aircraft Surface Finisher',
  'Airman',
  'Airport Controller',
  'Airport Manager',
  'Almoner',
  'Ambulance Controller',
  'Ambulance Crew',
  'Ambulance Driver',
  'Amusement Arcade Worker',
  'Anaesthetist',
  'Analyst',
  'Analytical Chemist',
  'Animal Breeder',
  'Anthropologist',
  'Antique Dealer',
  'Applications Engineer',
  'Applications Programmer',
  'Arbitrator',
  'Arborist',
  'Archaeologist',
  'Architect',
  'Archivist',
  'Area Manager',
  'Armourer',
  'Aromatherapist',
  'Art Critic',
  'Art Dealer',
  'Art Historian',
  'Art Restorer',
  'Artexer',
  'Artist',
  'Arts',
  'Assembly Worker',
  'Assessor',
  'Assistant',
  'Assistant Caretaker',
  'Assistant Cook',
  'Assistant Manager',
  'Assistant Nurse',
  'Assistant Teacher',
  'Astrologer',
  'Astronomer',
  'Attendant',
  'Au Pair',
  'Auction Worker',
  'Auctioneer',
  'Audiologist',
  'Audit Clerk',
  'Audit Manager',
  'Auditor',
  'Auto Electrician',
  'Auxiliary Nurse',
  'Bacon Curer',
  'Baggage Handler',
  'Bailiff',
  'Baker',
  'Bakery Assistant',
  'Bakery Manager',
  'Bakery Operator',
  'Balloonist',
  'Bank Clerk',
  'Bank Manager',
  'Bank Messenger',
  'Baptist Minister',
  'Bar Manager',
  'Bar Steward',
  'Barber',
  'Barmaid',
  'Barman',
  'Barrister',
  'Beautician',
  'Beauty Therapist',
  'Betting Shop',
  'Bill Poster',
  'Bingo Caller',
  'Biochemist',
  'Biologist',
  'Blacksmith',
  'Blind Assembler',
  'Blind Fitter',
  'Blinds Installer',
  'Boat Builder',
  'Body Fitter',
  'Bodyguard',
  'Bodyshop',
  'Book Binder',
  'Book Seller',
  'Book-Keeper',
  'Booking Agent',
  'Booking Clerk',
  'Bookmaker',
  'Botanist',
  'Branch Manager',
  'Breeder',
  'Brewer',
  'Brewery Manager',
  'Brewery Worker',
  'Bricklayer',
  'Broadcaster',
  'Builder',
  'Builders Labourer',
  'Building Advisor',
  'Building Control',
  'Building Engineer',
  'Building Estimator',
  'Building Foreman',
  'Building Inspector',
  'Building Manager',
  'Building Surveyor',
  'Bursar',
  'Bus Company',
  'Bus Conductor',
  'Bus Driver',
  'Bus Mechanic',
  'Bus Valeter',
  'Business Consultant',
  'Business Proprietor',
  'Butcher',
  'Butchery Manager',
  'Butler',
  'Buyer',
  'Cab Driver',
  'Cabinet Maker',
  'Cable Contractor',
  'Cable Jointer',
  'Cable TV Installer',
  'Cafe Owner',
  'Cafe Staff',
  'Cafe Worker',
  'Calibration Manager',
  'Camera Repairer',
  'Cameraman',
  'Car Dealer',
  'Car Delivery Driver',
  'Car Park Attendant',
  'Car Salesman',
  'Car Valet',
  'Car Wash Attendant',
  'Care Assistant',
  'Care Manager',
  'Careers Advisor',
  'Careers Officer',
  'Caretaker',
  'Cargo Operator',
  'Carpenter',
  'Carpet Cleaner',
  'Carpet Fitter',
  'Carpet Retailer',
  'Carphone Fitter',
  'Cartographer',
  'Cartoonist',
  'Cashier',
  'Casual Worker',
  'Caterer',
  'Catering Consultant',
  'Catering Manager',
  'Catering Staff',
  'Caulker',
  'Ceiling Contractor',
  'Ceiling Fixer',
  'Cellarman',
  'Chambermaid',
  'Chandler',
  'Chaplain',
  'Charge Hand',
  'Charity Worker',
  'Chartered',
  'Chartered Accountant',
  'Chauffeur',
  'Chef',
  'Chemist',
  'Chicken Chaser',
  'Child Minder',
  'Childminder',
  'Chimney Sweep',
  'China Restorer',
  'Chiropodist',
  'Chiropractor',
  'Choreographer',
  'Church Officer',
  'Church Warden',
  'Cinema Manager',
  'Circus Proprietor',
  'Circus Worker',
  'Civil Engineer',
  'Civil Servant',
  'Claims Adjustor',
  'Claims Assessor',
  'Claims Manager',
  'Clairvoyant',
  'Classroom Aide',
  'Cleaner',
  'Clergyman',
  'Cleric',
  'Clerk',
  'Commissioned',
  'Consultant',
  'Coroner',
  'Councillor',
  'Counsellor',
  'Dealer',
  'Decorator',
  'Delivery Driver',
  'Doctor',
  'Driver',
  'Economist',
  'Editor',
  'Employee',
  'Employment',
  'Engineer',
  'English Teacher',
  'Entertainer',
  'Envoy',
  'Executive',
  'Farmer',
  'Fireman',
  'Floor Layer',
  'Floor Manager',
  'Florist',
  'Flour Miller',
  'Flower Arranger',
  'Flying Instructor',
  'Foam Convertor',
  'Food Processor',
  'Footballer',
  'Foreman',
  'Forensic Scientist',
  'Forest Ranger',
  'Forester',
  'Fork Lift Truck Driver',
  'Forwarding Agent',
  'Foster Parent',
  'Foundry Worker',
  'Fraud Investigator',
  'French Polisher',
  'Fruiterer',
  'Fuel Merchant',
  'Fund Raiser',
  'Funeral Director',
  'Funeral Furnisher',
  'Furnace Man',
  'Furniture Dealer',
  'Furniture Remover',
  'Furniture Restorer',
  'Furrier',
  'Gallery Owner',
  'Gambler',
  'Gamekeeper',
  'Gaming Board Inspector',
  'Gaming Club Manager',
  'Gaming Club Proprietor',
  'Garage Attendant',
  'Garage Foreman',
  'Garage Manager',
  'Garda',
  'Garden Designer',
  'Gardener',
  'Gas Fitter',
  'Gas Mechanic',
  'Gas Technician',
  'Gate Keeper',
  'Genealogist',
  'General Practitioner',
  'Geologist',
  'Geophysicist',
  'Gilder',
  'Glass Worker',
  'Glazier',
  'Goldsmith',
  'Golf Caddy',
  'Golf Club Professional',
  'Golfer',
  'Goods Handler',
  'Governor',
  'Granite Technician',
  'Graphic Designer',
  'Graphologist',
  'Grave Digger',
  'Gravel Merchant',
  'Green Keeper',
  'Greengrocer',
  'Grocer',
  'Groom',
  'Ground Worker',
  'Groundsman',
  'Guest House Owner',
  'Guest House Proprietor',
  'Gun Smith',
  'Gynaecologist',
  'HGV Driver',
  'HGV Mechanic',
  'Hairdresser',
  'Handyman',
  'Hardware Dealer',
  'Haulage Contractor',
  'Hawker',
  'Health Advisor',
  'Health And Safety',
  'Health Care Assistant',
  'Health Consultant',
  'Health Nurse',
  'Health Planner',
  'Health Service',
  'Health Therapist',
  'Health Visitor',
  'Hearing Therapist',
  'Heating Engineer',
  'Herbalist',
  'Highway Inspector',
  'Hire Car Driver',
  'Historian',
  'History Teacher',
  'Hod Carrier',
  'Home Economist',
  'Home Help',
  'Homecare Manager',
  'Homeopath',
  'Homeworker',
  'Hop Merchant',
  'Horse Breeder',
  'Horse Dealer',
  'Horse Riding Instructor',
  'Horse Trader',
  'Horse Trainer',
  'Horticultural Consultant',
  'Horticulturalist',
  'Hosiery Mechanic',
  'Hosiery Worker',
  'Hospital Consultant',
  'Hospital Doctor',
  'Hospital Manager',
  'Hospital Orderly',
  'Hospital Technician',
  'Hospital Warden',
  'Hospital Worker',
  'Hostess',
  'Hot Foil Printer',
  'Hotel Consultant',
  'Hotel Worker',
  'Hotelier',
  'Househusband',
  'Housekeeper',
  'Housewife',
  'Housing Assistant',
  'Housing Officer',
  'Housing Supervisor',
  'Hygienist',
  'Hypnotherapist',
  'Hypnotist',
  'IT Consultant',
  'IT Manager',
  'IT Trainer',
  'Ice Cream Vendor',
  'Illustrator',
  'Immigration Officer',
  'Import Consultant',
  'Importer',
  'Independent Means',
  'Induction Moulder',
  'Industrial Chemist',
  'Industrial Consultant',
  'Injection Moulder',
  'Inspector',
  'Instructor',
  'Instrument Engineer',
  'Instrument Maker',
  'Instrument Supervisor',
  'Instrument Technician',
  'Insurance Agent',
  'Insurance Assessor',
  'Insurance Broker',
  'Insurance Consultant',
  'Insurance Inspector',
  'Insurance Staff',
  'Interior Decorator',
  'Interior Designer',
  'Interpreter',
  'Interviewer',
  'Inventor',
  'Investigator',
  'Investment Advisor',
  'Investment Banker',
  'Investment Manager',
  'Investment Strategist',
  'Ironmonger',
  'Janitor',
  'Jazz Composer',
  'Jeweller',
  'Jewellery',
  'Jockey',
  'Joiner',
  'Joinery Consultant',
  'Journalist',
  'Judge',
  'Keep Fit Instructor',
  'Kennel Hand',
  'Kitchen Worker',
  'Knitter',
  'Labelling Operator',
  'Laboratory Analyst',
  'Labourer',
  'Laminator',
  'Lampshade Maker',
  'Land Agent',
  'Land Surveyor',
  'Landlady',
  'Landlord',
  'Landowner',
  'Landworker',
  'Lathe Operator',
  'Laundry Staff',
  'Laundry Worker',
  'Lavatory Attendant',
  'Law Clerk',
  'Lawn Mower',
  'Lawyer',
  'Leaflet Distributor',
  'Leather Worker',
  'Lecturer',
  'Ledger Clerk',
  'Legal Advisor',
  'Legal Assistant',
  'Legal Executive',
  'Legal Secretary',
  'Letting Agent',
  'Liaison Officer',
  'Librarian',
  'Library Manager',
  'Licensed Premises',
  'Licensee',
  'Licensing',
  'Lifeguard',
  'Lift Attendant',
  'Lift Engineer',
  'Lighterman',
  'Lighthouse Keeper',
  'Lighting Designer',
  'Lighting Technician',
  'Lime Kiln Attendant',
  'Line Manager',
  'Line Worker',
  'Lineman',
  'Linguist',
  'Literary Agent',
  'Literary Editor',
  'Lithographer',
  'Litigation Manager',
  'Loans Manager',
  'Local Government',
  'Lock Keeper',
  'Locksmith',
  'Locum Pharmacist',
  'Log Merchant',
  'Lorry Driver',
  'Loss Adjustor',
  'Loss Assessor',
  'Lumberjack',
  'Machine Fitters',
  'Machine Minder',
  'Machine Operator',
  'Machine Setter',
  'Machine Tool',
  'Machine Tool Fitter',
  'Machinist',
  'Magician',
  'Magistrate',
  'Magistrates Clerk',
  'Maid',
  'Maintenance Fitter',
  'Make Up Artist',
  'Manicurist',
  'Manufacturing',
  'Map Mounter',
  'Marble Finisher',
  'Marble Mason',
  'Marine Broker',
  'Marine Consultant',
  'Marine Electrician',
  'Marine Engineer',
  'Marine Geologist',
  'Marine Pilot',
  'Marine Surveyor',
  'Market Gardener',
  'Market Research',
  'Market Researcher',
  'Market Trader',
  'Marketing Agent',
  'Marketing Assistant',
  'Marketing Coordinator',
  'Marketing Director',
  'Marketing Manager',
  'Marquee Erector',
  'Massage Therapist',
  'Masseur',
  'Masseuse',
  'Master Mariner',
  'Materials Controller',
  'Materials Manager',
  'Mathematician',
  'Maths Teacher',
  'Matron',
  'Mattress Maker',
  'Meat Inspector',
  'Meat Wholesaler',
  'Mechanic',
  'Medal Dealer',
  'Medical Advisor',
  'Medical Assistant',
  'Medical Consultant',
  'Medical Officer',
  'Medical Physicist',
  'Medical Practitioner',
  'Medical Researcher',
  'Medical Secretary',
  'Medical Student',
  'Medical Supplier',
  'Medical Technician',
  'Merchandiser',
  'Merchant',
  'Merchant Banker',
  'Merchant Seaman',
  'Messenger',
  'Metal Dealer',
  'Metal Engineer',
  'Metal Polisher',
  'Metal Worker',
  'Metallurgist',
  'Meteorologist',
  'Meter Reader',
  'Microbiologist',
  'Midwife',
  'Military Leader',
  'Milklady',
  'Milkman',
  'Mill Operator',
  'Mill Worker',
  'Miller',
  'Milliner',
  'Millwright',
  'Miner',
  'Mineralologist',
  'Minibus Driver',
  'Minicab Driver',
  'Mining Consultant',
  'Mining Engineer',
  'Money Broker',
  'Moneylender',
  'Mooring Contractor',
  'Mortgage Broker',
  'Mortician',
  'Motor Dealer',
  'Motor Engineer',
  'Motor Fitter',
  'Motor Mechanic',
  'Motor Racing',
  'Motor Trader',
  'Museum Assistant',
  'Museum Attendant',
  'Music Teacher',
  'Musician',
  'Nanny',
  'Navigator',
  'Negotiator',
  'Neurologist',
  'Newsagent',
  'Night Porter',
  'Night Watchman',
  'Nuclear Scientist',
  'Nun',
  'Nurse',
  'Nursery Assistant',
  'Nursery Nurse',
  'Nursery Worker',
  'Nurseryman',
  'Nursing Assistant',
  'Nursing Auxiliary',
  'Nursing Manager',
  'Nursing Sister',
  'Nutritionist',
  'Off Shore',
  'Office Manager',
  'Office Worker',
  'Oil Broker',
  'Oil Rig Crew',
  'Opera Singer',
  'Operations',
  'Operative',
  'Operator',
  'Optical',
  'Optical Advisor',
  'Optical Assistant',
  'Optician',
  'Optometrist',
  'Orchestral',
  'Organiser',
  'Organist',
  'Ornamental',
  'Ornithologist',
  'Orthopaedic',
  'Orthoptist',
  'Osteopath',
  'Outdoor Pursuits',
  'Outreach Worker',
  'Packaging',
  'Packer',
  'Paediatrician',
  'Paint Consultant',
  'Painter',
  'Palaeobotanist',
  'Palaeontologist',
  'Pallet Maker',
  'Panel Beater',
  'Paramedic',
  'Park Attendant',
  'Park Keeper',
  'Park Ranger',
  'Partition Erector',
  'Parts Man',
  'Parts Manager',
  'Parts Supervisor',
  'Party Planner',
  'Pasteuriser',
  'Pastry Chef',
  'Patent Agent',
  'Patent Attorney',
  'Pathologist',
  'Patrolman',
  'Pattern Cutter',
  'Pattern Maker',
  'Pattern Weaver',
  'Pawnbroker',
  'Payroll Assistant',
  'Payroll Clerk',
  'Payroll Manager',
  'Payroll Supervisor',
  'Personnel Officer',
  'Pest Controller',
  'Pet Minder',
  'Pharmacist',
  'Philatelist',
  'Photographer',
  'Physician',
  'Physicist',
  'Physiologist',
  'Physiotherapist',
  'Piano Teacher',
  'Piano Tuner',
  'Picture Editor',
  'Picture Framer',
  'Picture Reseacher',
  'Pig Man',
  'Pig Manager',
  'Pilot',
  'Pipe Fitter',
  'Pipe Inspector',
  'Pipe Insulator',
  'Pipe Layer',
  'Planning Engineer',
  'Planning Manager',
  'Planning Officer',
  'Planning Technician',
  'Plant Attendant',
  'Plant Driver',
  'Plant Engineer',
  'Plant Fitter',
  'Plant Manager',
  'Plant Operator',
  'Plasterer',
  'Plastics Consultant',
  'Plastics Engineer',
  'Plate Layer',
  'Plater',
  'Playgroup Assistant',
  'Playgroup Leader',
  'Plumber',
  'Podiatrist',
  'Police Officer',
  'Polisher',
  'Pool Attendant',
  'Pools Collector',
  'Porter',
  'Portfolio Manager',
  'Post Sorter',
  'Postman',
  'Postmaster',
  'Postwoman',
  'Potter',
  'Practice Manager',
  'Preacher',
  'Precision Engineer',
  'Premises',
  'Premises Security',
  'Press Officer',
  'Press Operator',
  'Press Setter',
  'Presser',
  'Priest',
  'Print Finisher',
  'Printer',
  'Prison Chaplain',
  'Prison Officer',
  'Private Investigator',
  'Probation Officer',
  'Probation Worker',
  'Procurator Fiscal',
  'Produce Supervisor',
  'Producer',
  'Product Installer',
  'Product Manager',
  'Production Engineer',
  'Production Hand',
  'Production Manager',
  'Production Planner',
  'Professional Boxer',
  'Professional Racing',
  'Professional Wrestler',
  'Progress Chaser',
  'Progress Clerk',
  'Project Co-ordinator',
  'Project Engineer',
  'Project Leader',
  'Project Manager',
  'Project Worker',
  'Projectionist',
  'Promoter',
  'Proof Reader',
  'Property Buyer',
  'Property Dealer',
  'Property Developer',
  'Property Manager',
  'Property Valuer',
  'Proprietor',
  'Psychiatrist',
  'Psychoanalyst',
  'Psychologist',
  'Psychotherapist',
  'Public House Manager',
  'Public Relations Of?cer',
  'Publican',
  'Publicity Manager',
  'Publisher',
  'Publishing Manager',
  'Purchase Clerk',
  'Purchase Ledger Clerk',
  'Purchasing Assistant',
  'Purchasing Manager',
  'Purser',
  'Quality Controller',
  'Quality Engineer',
  'Quality Inspector',
  'Quality Manager',
  'Quality Technician',
  'Quantity Surveyor',
  'Quarry Worker',
  'Racehorse Groom',
  'Racing Organiser',
  'Radio Controller',
  'Radio Director',
  'Radio Engineer',
  'Radio Operator',
  'Radio Presenter',
  'Radio Producer',
  'Radiographer',
  'Radiologist',
  'Rally Driver',
  'Receptionist',
  'Recorder',
  'Records Supervisor',
  'Recovery Vehicle Coordinator',
  'Recreational',
  'Recruitment Consultant',
  'Rector',
  'Reflexologist',
  'Refractory Engineer',
  'Refrigeration Engineer',
  'Refuse Collector',
  'Registrar',
  'Regulator',
  'Relocation Agent',
  'Remedial Therapist',
  'Rent Collector',
  'Rent Offcer',
  'Repair Man',
  'Repairer',
  'Reporter',
  'Representative',
  'Reprographic Assistant',
  'Research Analyst',
  'Research Consultant',
  'Research Director',
  'Research Scientist',
  'Research Technician',
  'Researcher',
  'Resin Caster',
  'Restaurant Manager',
  'Restaurateur',
  'Restorer',
  'Retired',
  'Revenue Clerk',
  'Revenue Officer',
  'Riding Instructor',
  'Rig Worker',
  'Rigger',
  'Riveter',
  'Road Safety Officer',
  'Road Sweeper',
  'Road Worker',
  'Roadworker',
  'Roof Tiler',
  'Roofer',
  'Rose Grower',
  'Royal Marine',
  'Rug Maker',
  'Saddler',
  'Safety Officer',
  'Sail Maker',
  'Sales Administrator',
  'Sales Assistant',
  'Sales Director',
  'Sales Engineer',
  'Sales Executive',
  'Sales Manager',
  'Sales Representative',
  'Sales Support',
  'Salesman',
  'Saleswoman',
  'Sand Blaster',
  'Saw Miller',
  'Scaffolder',
  'School Crossing',
  'School Inspector',
  'Scientific Officer',
  'Scientist',
  'Scrap Dealer',
  'Screen Printer',
  'Screen Writer',
  'Script Writer',
  'Sculptor',
  'Seaman',
  'Seamstress',
  'Secretary',
  'Security Consultant',
  'Security Controller',
  'Security Guard',
  'Security Officer',
  'Servant',
  'Service Engineer',
  'Service Manager',
  'Share Dealer',
  'Sheet Metal Worker',
  'Shelf Filler',
  'Shelter Warden',
  'Shepherd',
  'Sheriff',
  'Sheriff Clerk',
  'Sheriff Principal',
  'Shift Controller',
  'Ship Broker',
  'Ship Builder',
  'Shipping Clerk',
  'Shipping Officer',
  'Shipwright',
  'Shipyard Worker',
  'Shoe Maker',
  'Shoe Repairer',
  'Shooting Instructor',
  'Shop Assistant',
  'Shop Fitter',
  'Shop Keeper',
  'Shop Manager',
  'Shop Proprietor',
  'Shot Blaster',
  'Show Jumper',
  'Showman',
  'Shunter',
  'Sign Maker',
  'Signalman',
  'Signwriter',
  'Site Agent',
  'Site Engineer',
  'Skipper',
  'Slater',
  'Slaughterman',
  'Smallholder',
  'Social Worker',
  'Software Consultant',
  'Software Engineer',
  'Soldier',
  'Solicitor',
  'Song Writer',
  'Sound Artist',
  'Sound Engineer',
  'Sound Technician',
  'Special Constable',
  'Special Needs',
  'Speech Therapist',
  'Sports Administrator',
  'Sports Coach',
  'Sports Commentator',
  'Sportsman',
  'Sportsperson',
  'Sportswoman',
  'Spring Maker',
  'Stable Hand',
  'Staff Nurse',
  'Stage Director',
  'Stage Hand',
  'Stage Manager',
  'Stage Mover',
  'Station Manager',
  'Stationer',
  'Statistician',
  'Steel Erector',
  'Steel Worker',
  'Steeplejack',
  'Stenographer',
  'Steward',
  'Stewardess',
  'Stock Controller',
  'Stock Manager',
  'Stockbroker',
  'Stockman',
  'Stocktaker',
  'Stone Cutter',
  'Stone Sawyer',
  'Stonemason',
  'Store Detective',
  'Storeman',
  'Storewoman',
  'Street Entertainer',
  'Street Trader',
  'Stud Hand',
  'Student',
  'Student Nurse',
  'Student Teacher',
  'Studio Manager',
  'Sub-Postmaster',
  'Sub-Postmistress',
  'Supervisor',
  'Supply Teacher',
  'Surgeon',
  'Surveyor',
  'Systems Analyst',
  'Systems Engineer',
  'Systems Manager',
  'TV Editor',
  'Tachograph Analyst',
  'Tacker',
  'Tailor',
  'Tank Farm Operative',
  'Tanker Driver',
  'Tanner',
  'Tattooist',
  'Tax Advisor',
  'Tax Analyst',
  'Tax Assistant',
  'Tax Consultant',
  'Tax Inspector',
  'Tax Manager',
  'Tax Officer',
  'Taxi Controller',
  'Taxi Driver',
  'Taxidermist',
  'Tea Blender',
  'Tea Taster',
  'Teacher',
  'Teachers Assistant',
  'Technical Advisor',
  'Technical Analyst',
  'Technical Assistant',
  'Technical Author',
  'Technical Clerk',
  'Technical Co-ordinator',
  'Technical Director',
  'Technical Editor',
  'Technical Engineer',
  'Technical Illustrator',
  'Technical Instructor',
  'Technical Liaison',
  'Technical Manager',
  'Technician',
  'Telecommunication',
  'Telecommunications',
  'Telegraphist',
  'Telemarketeer',
  'Telephone Engineer',
  'Telephonist',
  'Telesales Person',
  'Television Director',
  'Television Engineer',
  'Television Presenter',
  'Television Producer',
  'Telex Operator',
  'Temperature Time',
  'Tennis Coach',
  'Textile Consultant',
  'Textile Engineer',
  'Textile Technician',
  'Textile Worker',
  'Thatcher',
  'Theatre Manager',
  'Theatre Technician',
  'Theatrical Agent',
  'Therapist',
  'Thermal Engineer',
  'Thermal Insulator',
  'Ticket Agent',
  'Ticket Inspector',
  'Tiler',
  'Timber Inspector',
  'Timber Worker',
  'Tobacconist',
  'Toll Collector',
  'Tool Maker',
  'Tour Agent',
  'Tour Guide',
  'Town Clerk',
  'Town Planner',
  'Toy Maker',
  'Toy Trader',
  'Track Worker',
  'Tractor Driver',
  'Tractor Mechanic',
  'Trade Mark Agent',
  'Trade Union Official',
  'Trading Standards',
  'Traffic Warden',
  'Train Driver',
  'Trainee Manager',
  'Training Advisor',
  'Training Assistant',
  'Training Co-ordinator',
  'Training Consultant',
  'Training Instructor',
  'Training Manager',
  'Training Officer',
  'Transcriber',
  'Translator',
  'Transport Clerk',
  'Transport Consultant',
  'Transport Controller',
  'Transport Engineer',
  'Transport Manager',
  'Transport Officer',
  'Transport Planner',
  'Travel Agent',
  'Travel Clerk',
  'Travel Consultant',
  'Travel Courier',
  'Travel Guide',
  'Travel Guide Writer',
  'Travel Representative',
  'Travelling Showman',
  'Treasurer',
  'Tree Feller',
  'Tree Surgeon',
  'Trichologist',
  'Trinity House Pilot',
  'Trout Farmer',
  'Tug Skipper',
  'Tunneller',
  'Turf Accountant',
  'Turkey Farmer',
  'Turner',
  'Tutor',
  'Typesetter',
  'Typewriter Engineer',
  'Typist',
  'Tyre Builder',
  'Tyre Fitter',
  'Tyre Inspector',
  'Tyre Technician',
  'Undertaker',
  'Underwriter',
  'Upholsterer',
  'Valuer',
  'Valve Technician',
  'Van Driver',
  'Vehicle Assessor',
  'Vehicle Body Worker',
  'Vehicle Engineer',
  'Vehicle Technician',
  'Ventriloquist',
  'Verger',
  'Veterinary Surgeon',
  'Vicar',
  'Video Artist',
  'Violin Maker',
  'Violinist',
  'Voluntary Worker',
  'Wages Clerk',
  'Waiter',
  'Waitress',
  'Warden',
  'Warehouse Manager',
  'Warehouseman',
  'Warehousewoman',
  'Watchmaker',
  'Weaver',
  'Weighbridge Clerk',
  'Weighbridge Operator',
  'Welder',
  'Welfare Assistant',
  'Welfare Officer',
  'Welfare Rights Officer',
  'Wheel Clamper',
  'Wholesale Newspaper',
  'Window Cleaner',
  'Window Dresser',
  'Windscreen Fitter',
  'Wine Merchant',
  'Wood Carver',
  'Wood Cutter',
  'Wood Worker',
  'Word Processing Operator',
  'Works Manager',
  'Writer',
  'Yacht Master',
  'Yard Manager',
  'Youth Hostel Warden',
  'Youth Worker',
  'Zoo Keeper',
  'Zoo Manager',
  'Zoologist'
];

const TERM1 = 'All candidates/employees are expected to register with valid '
    'information and verify their registration via the provided email.\n\nThere'
    ' would be no private discussion between the employee and employer on '
    'this platform.\n\nThere is no automatic employment on this platform after '
    'interview/test had been conducted.\n\nEmployment is subjected to '
    'employer’s'
    ' selection.\n\n10 percent of the candidate/employee salary will be paid '
    'into Workanetworks account in the next 6 months of  employment.\n'
    '\nOutright'
    ' payment for employee/candidate shall be 50 percent of his/her first '
    'salary.\n\nWorkanetorks will be responsible for the payment of salary of '
    'candidates that registered under workanetworks platform.\n\nNo candidate '
    'is allowed to leave his/her place of work without proper notification of'
    ' both the employer and the recruiting company.\n\nInterview/test shall be '
    'conducted on this platform after notification.Another Oral/practical '
    'interview may be conducted in your place of work after the online '
    'interview/test.\n\nAll candidates/employees shall behave politely with '
    'good character in their various place of work because all eyes shall be on them.';

const TERM2 = 'Employer/company must be registered on this platform with '
    'their corporate name.\n\nEmployer/company shall have access to the details'
    ' of the candidates except the contact details.\n\nInterview/ test shall be'
    ' conducted for all candidates on this platform using our Computer based '
    'system application.\n\nEmployer/company shall forward the test inform of '
    'objectives or theory to Workanetworks based on the position or '
    'assignment of the candidate.\n\nEmployer/company shall have access to our '
    'chat medium on the platform for enquiry, suggestions and observations.\n'
    '\nEmployer/company shall be charged for service based on premium '
    'subscribed for.';

const TERM3 = 'Features of the FREE\n\n-	Access to five shortlisted staff\n-	'
    'Access to unlimited choices of candidates\n-	Access to interview five '
    'candidates\n-	Access to online test/interview\n-	Free access to '
    'candidate anywhere in Nigeria\n\n\nFeatures of the SILVER PREMIUM (5,000'
    ' naira per Annum)\n\n-	Access to ten shortlisted staff\n-	Access to '
    'unlimited choices of candidates\n-	Access to interview ten candidates'
    '\n-Access to online test/interview\n-	Free access to candidate anywhere'
    ' in Nigeria\n\n\nFeatures of the GOLD PREMIUM (10,000 naira per Annum)\n'
    '\n-	Access to twenty shortlisted staff\n-	Access to unlimited choices '
    'of candidates\n-	Access to interview twenty candidates\n-	Access to '
    'online test/interview\n-	Free access to candidate anywhere in Nigeria'
    '\n\n\nFeatures of the DIAMOND (20,000 naira per Annum)\n\n-  Unlimited '
    'access to shortlist staff\n-	Unlimited access to choices of candidates'
    '\n-	Unlimited access to interview/test candidates\n-	Unlimited access '
    'to candidate anywhere in Nigeria';

const TERM4 = 'Salary of the candidates/employee shall be paid into '
    'Workanetworks account by the employer/company.\n\nWorkanetworks shall be '
    'responsible for the payment of salary to all the candidates that '
    'registered on the platform.\n\nAll candidates shall pay a service charge '
    'of 10% of their salary to Workanetworks for the next 6 months of '
    'employment.\n\nAny candidate/employee that wish to pay outright payment of'
    ' his/her service charge shall pay 50% from the first salary into '
    'Workanetworks account.\n\nWorkanetworks will not accept cash from any '
    'employer/company and we shall not send any of our staff to any '
    'employer/company to collect cash. This will ensure proper reconciliation'
    ' and accountability.\n\nA request shall be placed to all '
    'employer/company for the candidate’s salary every month according to the'
    ' agreed dates.\n\nEmployer/company shall make use of our payment gateway'
    ' on the platform for Any payment or transfer into Workanetworks account '
    'via every possible means.\n\nWorkanetworks will not be responsible for '
    'any candidate character or behavior.\n\nWorkanetwork only create a '
    'platform for employer to test the skills of the candidate/employee.';

const ABOUT1 =
    'Workanetworks is an online platform that offer recruitment services. We have a number of job vacancies for both graduates and non-graduates across all sectors; finances, academic, medical, aviation, constructions, maintenance, and many more. We can assist you in landing your dream job at the most convenient way you can ever imagine.\n\nWorkanetworks has simplified methods of securing job to the point that employees can search job, submit resume, apply for job and even attend interviews.  Employers can post or sponsored jobs, select the best candidates and also conduct interviews on their phone/tablets/PC. We connect job-seekers with jobs, employees with employers, aspiring professionals with professionals and students with tutors. Connecting is what we do best and at the easiest way.';

const ABOUT3 =
    'At Workanetworks Limited we provide the following products and services to our clients:\n\n1. Outsourcing\n2. Content creation ( CVs, Resume etc.)\n3. Educational services\n4. Human Resources\n5. Seminars\n6. Conferences';

const ABOUT2 =
    'The story of Workanetworks Limited started in 2019.\nWorkanetworks Limited aims to at all times maintain the upmost levels of service for our customers and strives to place itself at the forefront of recruiting, and outsourcing services .';

const ABOUT4 =
    'To simplify recruitment processes for both employers and employees.';

const ABOUT5 =
    'Our aim is to be the:\nNo-1 recruiting company in Africa.\nSimplify recruiting with the aid of technology\nOrganize seminar for better productivity.';

const ABOUT6 = 'Transparent\nExperts\nFlexible';

const PRIVACY1 =
    'Purpose\n\nThis policy affirms Worka Network’s belief in responsible, social and ethical behavior from all employees. This policy clarifies the standards of behavior that Workanetworks Limited  expects of all employees recruited through our company.\n\n\nPrinciples\n\n\nOur employees contribute to the success of our organization and that of our Clients is paramount and we not be taking for granted. Workanetworks Limited  fully endorse that all employees are not deprived of their basic human rights. Furthermore, our employees have an obligation to the Business, our Clients and themselves to observe high standards of integrity and fair dealing. Unlawful and unethical business practices undermine employee and Client trust\n\n\nPolicy\n\n\nOur Code of Conduct policy applies to all employees and provides the framework of principles for conducting business, dealing with other employees, Clients and suppliers. The Code of Conduct does not replace legislation and if any part of it is in conflict, then legislation takes precedence. This policy is based on the following:\n\nAct and maintain a high standard of integrity and professionalism Be responsible and scrupulous in the proper use of Company information, funds, equipment and facilities Be considerate and respectful of the environment and others Exercise fairness, equality, courtesy, consideration and sensitivity in dealing with other employees, clients and suppliers Avoid apparent conflict of interests, promptly disclosing to a Worka Network’s senior manager, any interest which may constitute a conflict of interest. Promote the interests of Workanetworks Perform duties with skill, honesty, care and diligence Abide by policies, procedures and lawful directions that relate to your employment with Workanetworks Limited  and/or our Clients Avoid the perception that any business transaction may be influenced by offering or accepting gifts. Under no circumstances may employees offer or accept money Any employee, who in good faith, raises a complaint or discloses an alleged breach of the Code, whilst following correct reporting procedures, will not be disadvantaged or prejudiced. All reports will be dealt with in a timely and confidential manner. Workanetworks Limited  expects co-operation from all employees in conducting themselves in a professional, ethical and socially acceptable manner of the highest standards. Any employee in breach of this policy may be subject to disciplinary action, including termination. Should an employee have doubts about any aspect of the Code of Conduct, they must seek clarification from the HR Manager.This policy will be regularly reviewed by Workanetworks Limited and any necessary changes will be implemented by the HR Manager.';

const PRIVACY2 =
    'Workanetworks Limited recognizes a robust and professional approach to recruitment, and selection helps us to attract and appoint individuals with the necessary skills and attributes to fulfill our aims and support our business goals.\n\nAll appointments should be made on the Principle of Merit, compliance with all relevant Federal and State Legislation and adherence to this policy and related processes.\n\nOur Business recruits people via the following methods:\n▪ Internal\n▪ External\n▪ Employee Referred\n▪ training plan\n▪ IT system orientation\n▪ policy and procedural requirements, e.g. equal employment opportunity';

const PRIVACY3 =
    'Workanetworks Limited will give employees adequate training to do their job safely and competently. Our business believes training is a two-way process. We encourage employees to participate and to highlight any gaps in their own skills or knowledge they believe they have. Training includes internal on-the-job training, written instructions such as standard operating procedures, coaching, external training and courses. Safety training takes precedence. Workanetworks Limited commits to providing every employee with trainings periodically as the needs arises.\n\nProbation Policy\nThe {3/6} month probationary period is a time for both the employee and the business to assess suitability, fit and competency within a role. During this period Workanetworks Limited commits to reviewing employee performance and at the end of this time ongoing permanent employment will be confirmed.';
//TESTING DATA